# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/Documents/GitHub/D5MWEB/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_rst_PS7_150M_0/zynq_soc_rst_PS7_150M_0.xci
# IP: The module: 'zynq_soc_rst_PS7_150M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Documents/GitHub/D5MWEB/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_rst_PS7_150M_0/zynq_soc_rst_PS7_150M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_soc_rst_PS7_150M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/Documents/GitHub/D5MWEB/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_rst_PS7_150M_0/zynq_soc_rst_PS7_150M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_soc_rst_PS7_150M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/Documents/GitHub/D5MWEB/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_rst_PS7_150M_0/zynq_soc_rst_PS7_150M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_soc_rst_PS7_150M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: z:/Documents/GitHub/D5MWEB/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_rst_PS7_150M_0/zynq_soc_rst_PS7_150M_0.xci
# IP: The module: 'zynq_soc_rst_PS7_150M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Documents/GitHub/D5MWEB/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_rst_PS7_150M_0/zynq_soc_rst_PS7_150M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_soc_rst_PS7_150M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/Documents/GitHub/D5MWEB/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_rst_PS7_150M_0/zynq_soc_rst_PS7_150M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_soc_rst_PS7_150M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: z:/Documents/GitHub/D5MWEB/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_rst_PS7_150M_0/zynq_soc_rst_PS7_150M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_soc_rst_PS7_150M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
