webtalk_init -webtalk_dir z:/zedboard/doc/ipmanager/managed_ip_project/managed_ip_project1.tmp/vfp_v1_0_v1_0_project/VFP_v1_0_v1_0_project.sim/sim_1/behav/xsim.dir/videoProcess_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 25 19:44:33 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.2_sdx (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1972098" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dc3b4485-1e7c-436e-9c5d-88a4127d27b8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "71e067e607104bc6b4635ea185038116" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "29.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3501 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "65.23_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "47936_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3388900396 -regid "210890246_0_0_143" -xml z:/zedboard/doc/ipmanager/managed_ip_project/managed_ip_project1.tmp/vfp_v1_0_v1_0_project/VFP_v1_0_v1_0_project.sim/sim_1/behav/xsim.dir/videoProcess_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html z:/zedboard/doc/ipmanager/managed_ip_project/managed_ip_project1.tmp/vfp_v1_0_v1_0_project/VFP_v1_0_v1_0_project.sim/sim_1/behav/xsim.dir/videoProcess_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm z:/zedboard/doc/ipmanager/managed_ip_project/managed_ip_project1.tmp/vfp_v1_0_v1_0_project/VFP_v1_0_v1_0_project.sim/sim_1/behav/xsim.dir/videoProcess_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
