// LAST TESTED : 12/16/2018
#include "utilities.h"
#include <stdio.h>
#include "uartio.h"
void cmds_menu() {
printf(
"\n"
"|--------------------------|\n"
"|D5M RELEASE V12.16.2018   |\n"
"|--------------------------|\n"
"|Hardware test             |\n"
"|--------------------------|\n"
"| cmds fifomode            |\n"
"| cmds readfifo            |\n"
"| cmds gridpoint           |\n"
"| cmds exposer             |\n"
"| cmds readexposer         |\n"
"| cmds readd5m             |\n"
"| cmds displaytype         |\n"
"| cmds printpixel          |\n"
"| cmds updated5m           |\n"
"| cmds configd5m           |\n"
"| cmds videochannel        |\n"
"| d5m testpattern          |\n"
"| d5m colorgain            |\n"
"| xbright                  |\n"
"| genimage                 |\n"
"| zoom                     |\n"
"| colorbars                |\n"
"| vga                      |\n"
"| hdmi                     |\n"
"| fullhdmi                 |\n"
"| coord                    |\n"
"| threshold                |\n"
"| timex                    |\n"
"|--------------------------|\n");
menu_print_prompt();
}
void master_menu() {
printf(
"o-completed , x- in progress\n"
"|------------------------|\n"
"|Hardware test           |\n"
"|------------------------|\n"
"|000|Chip Version        |\n"
"|001|Row Start           |\n"
"|002|Column Start        |\n"
"|003|Row Size            |\n"
"|004|Column Size         |\n"
"|005|Horizontal Blank    |\n"
"|006|Vertical Blank      |\n"
"|007|Output Control      |\n"
"|008|Shutter Width Upper |\n"
"|009|Shutter Width Lower |\n"
"|010|Pixel Clock Control |\n"
"|011|Restart             |\n"
"|012|Shutter Delay       |\n"
"|013|Reset               |\n"
"|016|PLL Control         |\n"
"|017|PLL Config 1        |\n"
"|018|PLL Config 2        |\n"
"|030|Read Mode 1         |\n"
"|032|Read Mode 2         |\n"
"|034|Row Address Mode    |\n"
"|035|Column address mode |\n"
"|043|Green1 Gain         |\n"
"|044|Blue Gain           |\n"
"|045|Red Gain            |\n"
"|046|Green2 Gain         |\n"
"|053|Global Gain         |\n"
"|075|Row black offset    |\n"
"|160|TestPatternControl  |\n"
"|161|Test Pattern Green  |\n"
"|162|Test Pattern Red    |\n"
"|163|Test Pattern Blue   |\n"
"|164|TestPatBarWidth     |\n"
"|255|Chip Version Alt    |\n"
"|------------------------|\n");
menu_print_prompt();
}
void menu_cls() {
printf("\033[2J\033[;H");
}