# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: Z:/ZEDBOARD/constraints/d5m_camera.xdc

# XDC: Z:/ZEDBOARD/constraints/target_pins.xdc

# Block Designs: bd/zynq_soc/zynq_soc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc || ORIG_REF_NAME==zynq_soc}]

# IP: bd/zynq_soc/ip/zynq_soc_CLK_GEN_148MHZ_0/zynq_soc_CLK_GEN_148MHZ_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_CLK_GEN_148MHZ_0 || ORIG_REF_NAME==zynq_soc_CLK_GEN_148MHZ_0}]

# IP: bd/zynq_soc/ip/zynq_soc_DIP_SWITCHES_8BITS_0/zynq_soc_DIP_SWITCHES_8BITS_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_DIP_SWITCHES_8BITS_0 || ORIG_REF_NAME==zynq_soc_DIP_SWITCHES_8BITS_0}]

# IP: bd/zynq_soc/ip/zynq_soc_LEDS_8BITS_0/zynq_soc_LEDS_8BITS_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_LEDS_8BITS_0 || ORIG_REF_NAME==zynq_soc_LEDS_8BITS_0}]

# IP: bd/zynq_soc/ip/zynq_soc_GND_1/zynq_soc_GND_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_GND_1 || ORIG_REF_NAME==zynq_soc_GND_1}]

# IP: bd/zynq_soc/ip/zynq_soc_TIMMING_CONTROLELR_0/zynq_soc_TIMMING_CONTROLELR_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_TIMMING_CONTROLELR_0 || ORIG_REF_NAME==zynq_soc_TIMMING_CONTROLELR_0}]

# IP: bd/zynq_soc/ip/zynq_soc_VCC_1/zynq_soc_VCC_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_VCC_1 || ORIG_REF_NAME==zynq_soc_VCC_1}]

# IP: bd/zynq_soc/ip/zynq_soc_VIDEO_OUT_0/zynq_soc_VIDEO_OUT_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_VIDEO_OUT_0 || ORIG_REF_NAME==zynq_soc_VIDEO_OUT_0}]

# IP: bd/zynq_soc/ip/zynq_soc_rst_PS7_150M_0/zynq_soc_rst_PS7_150M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_rst_PS7_150M_0 || ORIG_REF_NAME==zynq_soc_rst_PS7_150M_0}]

# IP: bd/zynq_soc/ip/zynq_soc_rst_PS7_75M_0/zynq_soc_rst_PS7_75M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_rst_PS7_75M_0 || ORIG_REF_NAME==zynq_soc_rst_PS7_75M_0}]

# IP: bd/zynq_soc/ip/zynq_soc_VDMA1_0/zynq_soc_VDMA1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_VDMA1_0 || ORIG_REF_NAME==zynq_soc_VDMA1_0}]

# IP: bd/zynq_soc/ip/zynq_soc_PS7_0/zynq_soc_PS7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_PS7_0 || ORIG_REF_NAME==zynq_soc_PS7_0}]

# IP: bd/zynq_soc/ip/zynq_soc_PS7_axi_periph_0/zynq_soc_PS7_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_PS7_axi_periph_0 || ORIG_REF_NAME==zynq_soc_PS7_axi_periph_0}]

# IP: bd/zynq_soc/ip/zynq_soc_Sine_0_0/zynq_soc_Sine_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_Sine_0_0 || ORIG_REF_NAME==zynq_soc_Sine_0_0}]

# IP: bd/zynq_soc/ip/zynq_soc_axi_mem_intercon_0/zynq_soc_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_axi_mem_intercon_0 || ORIG_REF_NAME==zynq_soc_axi_mem_intercon_0}]

# IP: bd/zynq_soc/ip/zynq_soc_xbar_1/zynq_soc_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_xbar_1 || ORIG_REF_NAME==zynq_soc_xbar_1}]

# IP: bd/zynq_soc/ip/zynq_soc_xbar_0/zynq_soc_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_xbar_0 || ORIG_REF_NAME==zynq_soc_xbar_0}]

# IP: bd/zynq_soc/ip/zynq_soc_VFP_0/zynq_soc_VFP_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_VFP_0 || ORIG_REF_NAME==zynq_soc_VFP_0}]

# IP: bd/zynq_soc/ip/zynq_soc_GND_0/zynq_soc_GND_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_GND_0 || ORIG_REF_NAME==zynq_soc_GND_0}]

# IP: bd/zynq_soc/ip/zynq_soc_HDMI_0/zynq_soc_HDMI_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_HDMI_0 || ORIG_REF_NAME==zynq_soc_HDMI_0}]

# IP: bd/zynq_soc/ip/zynq_soc_HDMI_IIC_0/zynq_soc_HDMI_IIC_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_HDMI_IIC_0 || ORIG_REF_NAME==zynq_soc_HDMI_IIC_0}]

# IP: bd/zynq_soc/ip/zynq_soc_D5M_IIC_0/zynq_soc_D5M_IIC_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_D5M_IIC_0 || ORIG_REF_NAME==zynq_soc_D5M_IIC_0}]

# IP: bd/zynq_soc/ip/zynq_soc_VCC_0/zynq_soc_VCC_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_VCC_0 || ORIG_REF_NAME==zynq_soc_VCC_0}]

# IP: bd/zynq_soc/ip/zynq_soc_auto_pc_1/zynq_soc_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_auto_pc_1 || ORIG_REF_NAME==zynq_soc_auto_pc_1}]

# IP: bd/zynq_soc/ip/zynq_soc_auto_cc_1/zynq_soc_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_auto_cc_1 || ORIG_REF_NAME==zynq_soc_auto_cc_1}]

# IP: bd/zynq_soc/ip/zynq_soc_auto_cc_0/zynq_soc_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_auto_cc_0 || ORIG_REF_NAME==zynq_soc_auto_cc_0}]

# IP: bd/zynq_soc/ip/zynq_soc_auto_pc_0/zynq_soc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_soc_auto_pc_0 || ORIG_REF_NAME==zynq_soc_auto_pc_0}]

# XDC: bd/zynq_soc/zynq_soc_ooc.xdc
